# Generated by Django 5.1.7 on 2025-03-28 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('otp_email', '0006_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmailDevice',
            fields=[
                ('emaildevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_email.emaildevice')),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('otp_email.emaildevice',),
        ),
    ]
