# Generated by Django 5.1.7 on 2025-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customemaildevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
