# Generated by Django 5.1.7 on 2025-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_securefile_fileshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='encrypted_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
