# Generated by Django 5.1.7 on 2025-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fileshare_encrypted_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='recipient_encrypted_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='recipient_password_set',
            field=models.BooleanField(default=False),
        ),
    ]
