# Generated by Django 5.1.7 on 2025-03-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_fileshare_recipient_encrypted_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
