# Generated by Django 5.1.7 on 2025-04-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_private_key_userprofile_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileshare',
            name='recipient_encrypted_key',
        ),
        migrations.RemoveField(
            model_name='fileshare',
            name='recipient_password_set',
        ),
        migrations.AddField(
            model_name='securefile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securefile',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
