# Generated by Django 5.1.7 on 2025-04-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_fileshare_recipient_encrypted_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_verification_count',
            field=models.IntegerField(default=0),
        ),
    ]
