# Generated by Django 5.1.7 on 2025-04-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_activitylog_delete_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
