# Generated by Django 5.1.7 on 2025-04-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_activitylog_city_alter_activitylog_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
