# Generated by Django 5.1.7 on 2025-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_login_attempts_userprofile_otp_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
